# Site settings
title: Kevin Yili Hong
email: hong@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a professor in the W. P. Carey School of Business. This website includes information about my research, teaching, and my collections of mechnical keyboards.
baseurl:  # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site
# twitter_username: stevenvmiller
github_username:  yilihong
orcid_id: 0000-0003-4072-6263
google_scholar_id: VwQmUFQAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Associate Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: "https://plus.google.com/u/0/110288225974212014913"
# google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
# bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins:
  - jekyll-sitemap
